export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const PRODUCT_REQUEST = "PRODUCT_REQUEST";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";

//login

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

//product details
export const FETCH_PRODUCT_DETAILS = "FETCH_PRODUCT_DETAILS";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";

// cart page

export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";


// orders page

export const ADD_ORDER = "ADD_ORDER";
